openapi: 3.0.0
info:
  title: BUKS API
  version: 0.0.1
  description: The API docs for BUKS
paths:
  /api/v1/auth/register:
    post:
      tags:
        - Authentication
      description: Creates a new user account
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: User account registration
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
        "400":
          $ref: "#/components/responses/GenericError"
  /api/v1/auth/login:
    post:
      tags:
        - Authentication
      description: Get the user authentication token
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User login response
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "400":
          $ref: "#/components/responses/GenericError"
  /api/v1/auth/reset-password:
    post:
      tags:
        - Authentication
      description: resets user password
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                oldPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        "200":
          description: password successfully reset/updated
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
        "400":
          $ref: "#/components/responses/GenericError"
components:
  schemas:
    User:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        membershipType:
          type: string
        email:
          type: string
        password:
          type: string
          format: password
    Error:
      type: object
      properties:
        error:
          type: string
  responses:
    GenericError:
      description: Error object
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Error"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT